name: Call Reusable Auto PR Workflow

on:
  push:
    branches-ignore:
      - main
      - uat
  pull_request:
    types: [closed]

jobs:
  auto-pr:
    uses: AshiqurRahaman02/org-workflows/.github/workflows/reusable-workflow.yml@main
    with:
      target_branch: "uat"
    secrets:
      github_token: ${{ secrets.SECRET_GITHUB_TOKEN }}
